default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: alexandria_development_db
  pool: 5
  host: 127.0.0.1
  username: alexandria_development_user
  password: digitalsynapse

test:
  adapter: postgresql
  encoding: unicode
  database: alexandria_test_db
  pool: 5
  host: 127.0.0.1
  username: alexandria_test_user
  password: aa9de59f54f4ebc57dcc

production:
  adapter: postgresql
  encoding: unicode
  database: alexandria_db
  pool: 5
  host: 127.0.0.1
  username: alexandria_user
  password: bda28b03ccf588986a8d
