default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: alexandria_development_db
  pool: 5
  host: 127.0.0.1
  username: alexandria_development_user
  password: digitalsynapse

test:
  adapter: postgresql
  encoding: unicode
  database: alexandria_test_db
  pool: 5
  host: 127.0.0.1
  username: alexandria_test_user
  password: 852c6d6329ea5951db16

production:
  adapter: postgresql
  encoding: unicode
  database: alexandria_db
  pool: 5
  host: 127.0.0.1
  username: alexandria_user
  password: 20b4a1224a3be547ed13
