# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 205a283e216c2a596ce0d301c4dd118e62841587631973f3c26b0c01f63ef1777d5b0cc17b142ab70b675ed1e53a5496665d1c5adf3ae17e6c59f2269a2fb047

test:
  secret_key_base: d61326d127fde090c21e6a07da3677349db487fd27e21213ebce0d7314f5f8839c439142277f3f1f4a4f51288b0adad67a84358bbb71b1913f6444056c56d617

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
